name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        mod: [starter]
    name: Build ${{ matrix.mod }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run -r build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.mod }}
          path: templates/${{ matrix.mod }}/dist
          if-no-files-found: error
